crud/urls.py
from django.contrib import admin
from django.urls import path
import blog.views
import account.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.main, name='main'),
    path('detail/<str:id>', blog.views.detail, name='detail'),
    path('read/', blog.views.read, name = 'read'),
    path('new/create/', blog.views.create, name='create'),
    path('edit/<str:id>', blog.views.edit, name='edit'),
    path('delete/<str:id>', blog.views.delete, name='delete'),
    path('hashtag/', blog.views.hashtagform, name='hashtag'),
    path('search/<int:hashtag_id>/', blog.views.search, name='search'),
    path('signup/', account.views.signup, name='signup'),
    path('login/', account.views.login, name='login'),
    path('logout/', account.views.logout, name='logout'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.TextField(max_length=10)
    email = models.TextField(max_length=20, null=True)
    phonenum = models.IntegerField(null=True)

blog/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateField('date published')
    writer = models.CharField(max_length=20, default='이름을 입력해주세요')
    content = models.TextField()
    hashtags = models.ManyToManyField('Hashtag', blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    def __str__(self):
        return self.text

    post_id = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    text= models.CharField(max_length=50)

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Post,Comment, Hashtag

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'writer', 'content', 'hashtags']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

account/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm 
from .models import Profile
from django.contrib.auth.models import User 

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if request.POST['password1'] == request.POST["password2"]:
            user = User.objects.create_user(
                username=request.POST["username"],
                password=request.POST["password1"])
            nickname = request.POST["nickname"]
            email = request.POST["email"]
            phonenum = request.POST["phonenum"]
            profile = Profile(user=user, nickname=nickname, email=email, phonenum=phonenum)
            profile.save()
            auth.login(request, user)
            return redirect('main')
        else:
            return render(request, 'signup.html', {'form':form})
    else :
        form = UserCreationForm()
        return render(request, 'signup.html', {'form':form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect(request, 'login.html', {'form':form})
        else:
            return render(request, 'login.html', {'form':form})
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form':form})

def logout(request):
    auth.logout(request)
    return redirect('main') 

blog/views.py
from django.core.checks.messages import Error
from blog.forms import PostForm, CommentForm, HashtagForm
from django.shortcuts import render, redirect, get_object_or_404
from .models import Comment, Hashtag, Post
from django.utils import timezone

# Create your views here.

#메인페이지
def main(request):
    return render(request, 'main.html')

#글쓰기페이지
def write(request):
    return render(request, 'write.html')

#글쓰기 함수
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.pub_date = timezone.now()
            form.save()
            form.save_m2m()
            return redirect('read')
    else:
        form = PostForm
        return render(request, 'write.html', {'form':form})

#읽기페이지
def read(request):
    posts = Post.objects
    hashtags = Hashtag.objects
    return render(request, 'read.html', {'posts':posts, 'hashtags':hashtags})

#디테일페이지 댓글함수
def detail(request, id):
    post = get_object_or_404(Post, id = id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post_id = post
            comment.text = form.cleaned_data['text']
            comment.save()
            return redirect('detail', id)
    else:
        form=CommentForm()
        return render(request, 'detail.html', {'post':post, 'form':form} )

#수정페이지
def edit(request, id):
    post = get_object_or_404(Post, id = id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save(commit=False)
            form.save()
            return redirect('read')
    else:
        form = PostForm(instance=post)
        return render(request, 'edit.html', {'form':form})


#삭제 함수
def delete(request, id):
    post = get_object_or_404(Post, id = id)
    post.delete()
    return redirect('read')

#해시태그 함수
def hashtagform(request, hashtag=None):
    if request.method == "POST":
        form = HashtagForm(request.POST, instance=hashtag)
        if form.is_valid():
            hashtag = form.save(commit=False)
            if Hashtag.objects.filter(name=form.cleaned_data['name']):
                form = HashtagForm()
                error_message = "이미 존재하는 해시태그 입니다."
                return render(request, 'hashtag.html', {'form':form, "error_message":error_message})
            else:
                hashtag.name = form.cleaned_data['name']
                hashtag.save()
            return redirect('main')
    else:
        form = HashtagForm(instance=hashtag)
        return render(request, 'hashtag.html', {'form':form} )

#검색 함수
def search(request, hashtag_id):
    blog = Post.objects
    hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
    return render(request, 'search.html', {'blog':blog, 'hashtag':hashtag})

account/templates/login.html
{% extends 'base.html' %} 

{% block content %} 
    <form method="post" action="{%url 'login' %}">
        {% csrf_token %} 
        {{ form.as_p }}
        <button type="submit">로그인</button>
    </form>
{% endblock %} 

account/templates/signup.html
{% extends 'base.html' %} 

{% block content %} 
    <form method="post" action="{%url 'signup' %}">
        {% csrf_token %} 
        Username : 
        <br>
        <input name='username' type="text">
        <br>
        Password : 
        <br>
        <input name='password1' type="password">
        <br>
        Confirm Password : 
        <br>
        <input name='password2' type="password">
        <br>
        Nickname : 
        <br>
        <input name='nickname' type="nickname">
        <br>
        Email : 
        <br>
        <input name='email' type="email">
        <br>
        Phone Number : 
        <br>
        <input name='phonenum' type="phonenum">
        <br>
        <br>
        <button type="submit">가입</button>
    </form>
{% endblock %} 

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Grayscale - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">LIKELION9 AT SKHU</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'main' %}">Main</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'create' %}">Write</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'read' %}">list</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'hashtag' %}">Add hashtag</a></li>
                    
                        {% if user.is_active %}
                            <li class="nav-item"><a clase="nav-link"> {{ user.profile.nickname }}님 안녕하세요 </a></li>
                            <li class="nav-item"><a clase="nav-link" href="{% url 'logout' %}"> logout </a></li>
                        {% else %} 
                            <li class="nav-item"><a clase="nav-link" href="{% url 'signup' %}"> 회원가입 </a></li>
                            <li class="nav-item"><a clase="nav-link" href="{% url 'login' %}"> 로그인 </a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        <h1 class="mx-auto my-0 text-uppercase">LIKELION9 AT SKHU</h1>
                        <h2 class="text-white-50 mx-auto mt-2 mb-5">CRUD Training</h2>
                        {% block createButton %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; LIKELION 9th 2021</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

blog/templates/detail.html
{% extends 'base.html' %}
{% block content %}

    <h2 class="text-center mt-0">제목 : {{post.title}}</h2>
    <hr class="divider" />
    <div class="text-center mt-0">
    <p>작성 일자: {{ post.pub_date }}</p>
    <p>글쓴이 : {{ post.writer }}</p>
    <p>내용 : {{ post.content }}</p>
    <button class="button" type="submit"><a href="{% url 'edit' post.id %}">수정하기</a></button>
    <button class="button" type="submit"><a href="{% url 'delete' post.id %}">삭제하기</a></button>
    <br><br>
    <!-- 해시태그 불러오기 -->
    {% for hashtags in post.hashtags.all %}
        <span>{{ hashtags.name }}</span>
    {% endfor %}
    <br>
    <!-- 댓글 불러오기 -->
    {% for comment in post.comments.all %}
        <p>{{ comment.text }}</p>
    {% endfor %}

    <br><br>
    <form method="POST" action="{% url 'detail' post.id %}">
        {% csrf_token %}
        <p>{{ form.as_p }}</p>
        <input type="submit" value="submit">
    </form>
    </div>
{% endblock %}

blog/templates/edit.html
{% extends 'base.html' %}
{% block content %}

    <form method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button class="btn btn-primary btn-xl" type="submit">작성</button>
    </form>
            
{% endblock %}

blog/templates/hashtag.html
{% extends 'base.html' %}
{% block content %}
<div class="input-group-text">
    <h1>New Hashtag</h1>
    <form method="POST">
        {{ error_message }}
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button class="btn btn-primary btn-xl" type="submit">작성</button>
    </form>
</div> 
{% endblock %}

blog/templates/main.html
{% extends 'base.html' %}
{% block createButton %}
<a class="btn btn-primary" href="{% url 'create' %}">Write</a>
{% endblock %}

blog/templates/read.html
{% extends 'base.html' %}
{% block content %}

    <h2 class="text-center mt-0">List</h2>
    <hr class="divider" />

    <h4>Hashtag 검색</h4>
    <h6>Hashtag를 클릭하시면 해당 Hashtag가 포함된 글 목록을 보실 수 있습니다</h6>

    {% for hashtag in hashtags.all %}
    <a class="btn btn-primary" href="{% url 'search' hashtag.id %}">{{ hashtag.name }}</a>
    {% endfor %}

    <br><br>
    {% for posts in posts.all %}
    <p>제목 :<a href="{% url 'detail' posts.id %}">{{ posts.title }}</a></p>
    <p>작성자 : {{ posts.writer }}</p>
    <p>작성 일자 : {{ posts.pub_date }}</p>
    <br>
    {% endfor %}
    </div></div>
    

    
{% endblock %}

blog/templates/search.html
{% extends 'base.html' %}
{% block content %}

    <h2 class="text-center mt-0">{{ hashtag }} 해시태그가 있는 게시글 목록</h2>
    <hr class="divider" />
    
    
    {% for blog in hashtag.post_set.all %}
    <p>제목 :<a href="{% url 'detail' blog.id %}">{{ blog.title }}</a></p>
    <p>작성자 : {{ blog.writer }}</p>
    <p>작성 일자 : {{ blog.pub_date }}</p>
    <br>
    {% endfor %}
    </div></div>
    
{% endblock %}

blog/templates/write.html
{% extends 'base.html' %}
{% block content %}
<div class="input-group-text">
    <form method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button class="btn btn-primary btn-xl" type="submit">작성</button>
    </form>
</div> 
{% endblock %}